server:
  port: 8080
  connection-timeout: 5000
spring: 
  jackson:
    serialization:
      write-dates-as-timestamps: false
  application: 
    name: product
  rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
